spring:
  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html
  thymeleaf:
    cache: false
  application:
    name: ms-srm-expfilter
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/
    instance:
      prefer-ip-address: false
server:
  port: 8089
  max-http-header-size: 4048576
