spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ms_srm_exp?characterEncoding=utf-8
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 6000

  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html
server:
  port: 8089
